import {
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'fs';
import { basename, dirname, join, relative, resolve } from 'path';

const START_MARKER = '// region generated-constract-type-exports:start';
const END_MARKER = '// region generated-constract-type-exports:end';
const srcRoot = resolve(process.cwd(), 'src');
const GENERATED_SUFFIX = '.types.generated.ts';
const GENERATED_DIR = 'types';

function toPosixPath(pathValue: string): string {
  return pathValue.split('\\').join('/');
}

function toPascalCase(input: string): string {
  return input
    .replace(/(^|_|-)([a-z])/g, (_match, _sep, char: string) =>
      char.toUpperCase()
    )
    .replace(/[^a-zA-Z0-9]/g, '');
}

function inferSchemaAlias(schemaName: string): string {
  const baseName = schemaName.replace(/Schema$/, '');
  if (baseName.endsWith('Body')) {
    return `${toPascalCase(baseName.slice(0, -4))}Params`;
  }
  if (baseName.endsWith('Response')) {
    return `${toPascalCase(baseName.slice(0, -8))}Result`;
  }
  return toPascalCase(baseName);
}

function collectExportedSchemas(source: string): string[] {
  const pattern = /export const (\w+Schema)\s*=/g;
  const names: string[] = [];
  let match = pattern.exec(source);
  while (match) {
    names.push(match[1]);
    match = pattern.exec(source);
  }
  return names;
}

function collectActionConstants(source: string): string[] {
  const pattern = /export const (\w+_ACTION)\s*=/g;
  const names: string[] = [];
  let match = pattern.exec(source);
  while (match) {
    names.push(match[1]);
    match = pattern.exec(source);
  }
  return names;
}

function actionTypeName(actionConstName: string): string {
  return toPascalCase(actionConstName.toLowerCase());
}

function cleanupGeneratedBlock(source: string): string {
  const hasMarkers =
    source.includes(START_MARKER) && source.includes(END_MARKER);
  if (!hasMarkers) return source;
  const blockPattern = new RegExp(
    `\\n?${START_MARKER}[\\s\\S]*?${END_MARKER}\\n?`,
    'm'
  );
  return source.replace(blockPattern, '\n').trimEnd() + '\n';
}

function buildGeneratedFileContent(
  importPathToSourceFile: string,
  schemaNames: string[],
  actionConstNames: string[]
): string {
  const importNames = [...actionConstNames, ...schemaNames];
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED FILE. DO NOT EDIT.');
  lines.push('// Generated by: scripts/generate-constract-type-exports.ts');
  lines.push("import { z } from 'zod';");
  lines.push(
    `import { ${importNames.join(', ')} } from '${importPathToSourceFile}';`
  );
  lines.push('');

  for (const actionConstName of actionConstNames) {
    const typeName = actionTypeName(actionConstName);
    lines.push(`export type ${typeName} =`);
    lines.push(
      `  (typeof ${actionConstName})[keyof typeof ${actionConstName}];`
    );
    lines.push('');
  }

  for (const schemaName of schemaNames) {
    const typeName = inferSchemaAlias(schemaName);
    lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
  }

  lines.push('');
  return lines.join('\n');
}

function shouldProcessFile(absolutePath: string): boolean {
  const rel = toPosixPath(relative(srcRoot, absolutePath));
  if (!rel.endsWith('.ts')) return false;
  if (rel.endsWith(GENERATED_SUFFIX)) return false;
  if (rel.includes(`/${GENERATED_DIR}/`) || rel.startsWith(`${GENERATED_DIR}/`))
    return false;
  if (rel.startsWith('constants/')) return false;
  if (rel.endsWith('/index.ts') || rel === 'index.ts') return false;
  return true;
}

function walkFiles(dir: string): string[] {
  const entries = readdirSync(dir);
  const files: string[] = [];
  for (const entry of entries) {
    const abs = join(dir, entry);
    const stat = statSync(abs);
    if (stat.isDirectory()) {
      files.push(...walkFiles(abs));
    } else {
      files.push(abs);
    }
  }
  return files;
}

function main(): void {
  const targetFiles = walkFiles(srcRoot).filter(shouldProcessFile);
  let updatedFileCount = 0;
  let generatedTypeCount = 0;
  const generatedFilesByDir = new Map<string, Set<string>>();

  for (const filePath of targetFiles) {
    const source = readFileSync(filePath, 'utf8');
    const schemaNames = collectExportedSchemas(source);
    const actionConstNames = collectActionConstants(source);
    if (schemaNames.length === 0 && actionConstNames.length === 0) {
      continue;
    }

    const cleanedSource = cleanupGeneratedBlock(source);
    if (cleanedSource !== source) {
      writeFileSync(filePath, cleanedSource, 'utf8');
      updatedFileCount += 1;
    }

    const sourceDir = dirname(filePath);
    const sourceBasenameNoExt = basename(filePath, '.ts');
    const generatedDirPath = join(sourceDir, GENERATED_DIR);
    mkdirSync(generatedDirPath, { recursive: true });
    const generatedPath = join(
      generatedDirPath,
      `${sourceBasenameNoExt}${GENERATED_SUFFIX}`
    );
    const generatedContent = buildGeneratedFileContent(
      `../${sourceBasenameNoExt}`,
      schemaNames,
      actionConstNames
    );
    writeFileSync(generatedPath, generatedContent, 'utf8');
    const generatedFileBasename = basename(generatedPath, '.ts');
    const existingGeneratedFiles =
      generatedFilesByDir.get(generatedDirPath) ?? new Set<string>();
    existingGeneratedFiles.add(generatedFileBasename);
    generatedFilesByDir.set(generatedDirPath, existingGeneratedFiles);

    generatedTypeCount += schemaNames.length + actionConstNames.length;
  }

  generatedFilesByDir.forEach((generatedFiles, generatedDirPath) => {
    const exportLines = Array.from(generatedFiles)
      .sort((leftName, rightName) => leftName.localeCompare(rightName))
      .map(generatedFile => `export * from './${generatedFile}';`);
    const indexContent =
      '// AUTO-GENERATED FILE. DO NOT EDIT.\n' +
      '// Generated by: scripts/generate-constract-type-exports.ts\n' +
      '\n' +
      `${exportLines.join('\n')}\n`;
    writeFileSync(join(generatedDirPath, 'index.ts'), indexContent, 'utf8');
  });

  process.stdout.write(
    `Updated ${updatedFileCount} files with ${generatedTypeCount} generated type exports.\n`
  );
}

main();
