services:
  idp-server:
    image: ghcr.io/lzstarv/csisp-idp-server:${IDP_SERVER_TAG}
    environment:
      NODE_ENV: production
      CSISP_IDP_PORT: ${CSISP_IDP_PORT}
      CSISP_IDP_RPC_URL: ${CSISP_IDP_RPC_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      OIDC_KEK_SECRET: ${OIDC_KEK_SECRET}
      IDP_COOKIE_DOMAIN: ${IDP_COOKIE_DOMAIN}
      IDP_ACCESS_TOKEN_EXPIRES_IN: ${IDP_ACCESS_TOKEN_EXPIRES_IN}
      IDP_REFRESH_TOKEN_EXPIRES_IN: ${IDP_REFRESH_TOKEN_EXPIRES_IN}
      SMS_SIGN_NAME: ${SMS_SIGN_NAME}
      SMS_TEMPLATE_CODE: ${SMS_TEMPLATE_CODE}
      SMS_SCHEME_NAME: ${SMS_SCHEME_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_NAMESPACE: ${REDIS_NAMESPACE}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${CSISP_IDP_PORT}:${CSISP_IDP_PORT}"
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:${CSISP_IDP_PORT}/api/idp/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  idp-client:
    image: ghcr.io/lzstarv/csisp-idp-client:${IDP_CLIENT_TAG}
    ports:
      - "8082:80"
    restart: unless-stopped
