packages:
  # 应用层 - 可独立部署的应用
  - 'apps/*'
  - 'apps/idp/client'
  - 'apps/idp/server'
  - 'infra/*'

  # 共享包层 - 可复用的代码模块
  - 'packages/*'

  # 工具配置层 - 开发工具和配置
  - 'tooling'

  # 文档层 - 项目文档和指南
  - 'docs'

  # 测试层 - 测试相关文件
  - 'tests'
