previews:
  generation: off
services:
  - type: web
    runtime: node
    name: backend-integrated
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/integrated-server
    startCommand: pnpm -F @csisp/integrated-server start
    envVars:
      - fromGroup: csisp-env-prod

  - type: web
    runtime: node
    name: bff
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/bff
    startCommand: pnpm -F @csisp/bff start
    envVars:
      - fromGroup: csisp-env-prod

  - type: web
    runtime: node
    name: idp-server
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/idp-server
    startCommand: pnpm -F @csisp/idp-server start
    healthCheckPath: /api/idp/health
    envVars:
      - fromGroup: csisp-env-prod

  - type: web
    runtime: static
    name: frontend-admin
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/admin
    staticPublishPath: apps/frontend/admin/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/admin/**
    routes:
      - type: rewrite
        source: /api/*
        destination: https://bff.onrender.com/api/

  - type: web
    runtime: static
    name: frontend-portal
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/portal
    staticPublishPath: apps/frontend/portal/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/portal/**
    routes:
      - type: rewrite
        source: /api/*
        destination: https://bff.onrender.com/api/

  - type: web
    runtime: static
    name: idp-client
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/idp-client
    staticPublishPath: apps/frontend/idp-client/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/idp-client/**
    routes:
      - type: rewrite
        source: /api/idp/*
        destination: https://idp-server.onrender.com/api/idp/

envVarGroups:
  - name: csisp-env-prod
    envVars: []
