previews:
  generation: off
services:
  - type: pserv
    runtime: node
    name: csisp-integrated-server
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/integrated-server
    startCommand: pnpm -F @csisp/integrated-server start
    envVars:
      - fromGroup: csisp-env-prod

  - type: web
    runtime: node
    name: csisp-bff
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/bff
    startCommand: pnpm -F @csisp/bff start
    envVars:
      - fromGroup: csisp-env-prod
      - key: INTEGRATED_SERVER_HOST
        fromService:
          name: csisp-integrated-server
          type: pserv
          envVarKey: RENDER_INTERNAL_HOSTNAME

  - type: web
    runtime: node
    name: csisp-idp-server
    plan: free
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/idp-server
    startCommand: pnpm -F @csisp/idp-server start
    healthCheckPath: /api/idp/health
    envVars:
      - fromGroup: csisp-env-prod

  - type: web
    runtime: static
    name: csisp-admin
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/admin
    staticPublishPath: apps/frontend/admin/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/admin/**
    routes:
      - type: rewrite
        source: /api/*
        destination: https://csisp-bff.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    runtime: static
    name: csisp-portal
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/portal
    staticPublishPath: apps/frontend/portal/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/portal/**
    routes:
      - type: rewrite
        source: /api/*
        destination: https://csisp-bff.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    runtime: static
    name: csisp-idp-client
    rootDir: .
    buildCommand: >
      pnpm i --frozen-lockfile &&
      turbo run build --filter=@csisp/idp-client
    staticPublishPath: apps/frontend/idp-client/dist
    envVars:
      - fromGroup: csisp-env-prod
    previews:
      generation: off
    buildFilter:
      paths:
        - apps/frontend/idp-client/**
    routes:
      - type: rewrite
        source: /api/*
        destination: https://csisp-bff.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

envVarGroups:
  - name: csisp-env-prod
    envVars: []
