create extension if not exists "hypopg" with schema "extensions";

create extension if not exists "index_advisor" with schema "extensions";


  create table "public"."trusted_frontends" (
    "id" bigint generated by default as identity not null,
    "origin" text not null,
    "enabled" boolean not null default true,
    "notes" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."trusted_frontends" enable row level security;

CREATE UNIQUE INDEX trusted_frontends_origin_key ON public.trusted_frontends USING btree (origin);

CREATE UNIQUE INDEX trusted_frontends_pkey ON public.trusted_frontends USING btree (id);

alter table "public"."trusted_frontends" add constraint "trusted_frontends_pkey" PRIMARY KEY using index "trusted_frontends_pkey";

alter table "public"."trusted_frontends" add constraint "trusted_frontends_origin_key" UNIQUE using index "trusted_frontends_origin_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.bff_get_trusted_frontends()
 RETURNS json
 LANGUAGE plpgsql
 STABLE
AS $function$declare
  v json;
begin
  select coalesce(json_agg(origin order by origin), '[]'::json)
    into v
  from public.trusted_frontends
  where enabled is true;
  return v;
end$function$
;

grant delete on table "public"."trusted_frontends" to "anon";

grant insert on table "public"."trusted_frontends" to "anon";

grant references on table "public"."trusted_frontends" to "anon";

grant select on table "public"."trusted_frontends" to "anon";

grant trigger on table "public"."trusted_frontends" to "anon";

grant truncate on table "public"."trusted_frontends" to "anon";

grant update on table "public"."trusted_frontends" to "anon";

grant delete on table "public"."trusted_frontends" to "authenticated";

grant insert on table "public"."trusted_frontends" to "authenticated";

grant references on table "public"."trusted_frontends" to "authenticated";

grant select on table "public"."trusted_frontends" to "authenticated";

grant trigger on table "public"."trusted_frontends" to "authenticated";

grant truncate on table "public"."trusted_frontends" to "authenticated";

grant update on table "public"."trusted_frontends" to "authenticated";

grant delete on table "public"."trusted_frontends" to "postgres";

grant insert on table "public"."trusted_frontends" to "postgres";

grant references on table "public"."trusted_frontends" to "postgres";

grant select on table "public"."trusted_frontends" to "postgres";

grant trigger on table "public"."trusted_frontends" to "postgres";

grant truncate on table "public"."trusted_frontends" to "postgres";

grant update on table "public"."trusted_frontends" to "postgres";

grant delete on table "public"."trusted_frontends" to "service_role";

grant insert on table "public"."trusted_frontends" to "service_role";

grant references on table "public"."trusted_frontends" to "service_role";

grant select on table "public"."trusted_frontends" to "service_role";

grant trigger on table "public"."trusted_frontends" to "service_role";

grant truncate on table "public"."trusted_frontends" to "service_role";

grant update on table "public"."trusted_frontends" to "service_role";


